# Generated by Django 2.2 on 2019-04-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrases',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
