# Generated by Django 2.2 on 2019-04-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0004_sentences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='phrase',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sentence',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
